export let styles = {
  item: {
    padding: '2px 6px',
    cursor: 'default'
  },

  highlightedItem: {
    color: 'white',
    background: 'hsl(200, 50%, 50%)',
    padding: '2px 6px',
    cursor: 'default'
  },

  menu: {
    border: 'solid 1px #ccc'
  }
};


export function removeDiacritics (str) {

    var defaultDiacriticsRemovalMap = [
        {'base':'A', 'letters':/[\u0041\u24B6\uFF21\u00C0\u00C1\u00C2\u1EA6\u1EA4\u1EAA\u1EA8\u00C3\u0100\u0102\u1EB0\u1EAE\u1EB4\u1EB2\u0226\u01E0\u00C4\u01DE\u1EA2\u00C5\u01FA\u01CD\u0200\u0202\u1EA0\u1EAC\u1EB6\u1E00\u0104\u023A\u2C6F]/g},
         {'base':'B', 'letters':/[\u0042\u24B7\uFF22\u1E02\u1E04\u1E06\u0243\u0182\u0181]/g},
        {'base':'C', 'letters':/[\u0043\u24B8\uFF23\u0106\u0108\u010A\u010C\u00C7\u1E08\u0187\u023B\uA73E]/g},
        {'base':'D', 'letters':/[\u0044\u24B9\uFF24\u1E0A\u010E\u1E0C\u1E10\u1E12\u1E0E\u0110\u018B\u018A\u0189\uA779]/g},
        {'base':'E', 'letters':/[\u0045\u24BA\uFF25\u00C8\u00C9\u00CA\u1EC0\u1EBE\u1EC4\u1EC2\u1EBC\u0112\u1E14\u1E16\u0114\u0116\u00CB\u1EBA\u011A\u0204\u0206\u1EB8\u1EC6\u0228\u1E1C\u0118\u1E18\u1E1A\u0190\u018E]/g},
        {'base':'F', 'letters':/[\u0046\u24BB\uFF26\u1E1E\u0191\uA77B]/g},
        {'base':'G', 'letters':/[\u0047\u24BC\uFF27\u01F4\u011C\u1E20\u011E\u0120\u01E6\u0122\u01E4\u0193\uA7A0\uA77D\uA77E]/g},
        {'base':'H', 'letters':/[\u0048\u24BD\uFF28\u0124\u1E22\u1E26\u021E\u1E24\u1E28\u1E2A\u0126\u2C67\u2C75\uA78D]/g},
        {'base':'I', 'letters':/[\u0049\u24BE\uFF29\u00CC\u00CD\u00CE\u0128\u012A\u012C\u0130\u00CF\u1E2E\u1EC8\u01CF\u0208\u020A\u1ECA\u012E\u1E2C\u0197]/g},
        {'base':'J', 'letters':/[\u004A\u24BF\uFF2A\u0134\u0248]/g},
        {'base':'K', 'letters':/[\u004B\u24C0\uFF2B\u1E30\u01E8\u1E32\u0136\u1E34\u0198\u2C69\uA740\uA742\uA744\uA7A2]/g},
        {'base':'L', 'letters':/[\u004C\u24C1\uFF2C\u013F\u0139\u013D\u1E36\u1E38\u013B\u1E3C\u1E3A\u0141\u023D\u2C62\u2C60\uA748\uA746\uA780]/g},
        {'base':'M', 'letters':/[\u004D\u24C2\uFF2D\u1E3E\u1E40\u1E42\u2C6E\u019C]/g},
        {'base':'N', 'letters':/[\u004E\u24C3\uFF2E\u01F8\u0143\u00D1\u1E44\u0147\u1E46\u0145\u1E4A\u1E48\u0220\u019D\uA790\uA7A4]/g},
        {'base':'O', 'letters':/[\u004F\u24C4\uFF2F\u00D2\u00D3\u00D4\u1ED2\u1ED0\u1ED6\u1ED4\u00D5\u1E4C\u022C\u1E4E\u014C\u1E50\u1E52\u014E\u022E\u0230\u00D6\u022A\u1ECE\u0150\u01D1\u020C\u020E\u01A0\u1EDC\u1EDA\u1EE0\u1EDE\u1EE2\u1ECC\u1ED8\u01EA\u01EC\u00D8\u01FE\u0186\u019F\uA74A\uA74C]/g},
        {'base':'P', 'letters':/[\u0050\u24C5\uFF30\u1E54\u1E56\u01A4\u2C63\uA750\uA752\uA754]/g},
        {'base':'Q', 'letters':/[\u0051\u24C6\uFF31\uA756\uA758\u024A]/g},
        {'base':'R', 'letters':/[\u0052\u24C7\uFF32\u0154\u1E58\u0158\u0210\u0212\u1E5A\u1E5C\u0156\u1E5E\u024C\u2C64\uA75A\uA7A6\uA782]/g},
        {'base':'S', 'letters':/[\u0053\u24C8\uFF33\u1E9E\u015A\u1E64\u015C\u1E60\u0160\u1E66\u1E62\u1E68\u0218\u015E\u2C7E\uA7A8\uA784]/g},
        {'base':'T', 'letters':/[\u0054\u24C9\uFF34\u1E6A\u0164\u1E6C\u021A\u0162\u1E70\u1E6E\u0166\u01AC\u01AE\u023E\uA786]/g},
        {'base':'U', 'letters':/[\u0055\u24CA\uFF35\u00D9\u00DA\u00DB\u0168\u1E78\u016A\u1E7A\u016C\u00DC\u01DB\u01D7\u01D5\u01D9\u1EE6\u016E\u0170\u01D3\u0214\u0216\u01AF\u1EEA\u1EE8\u1EEE\u1EEC\u1EF0\u1EE4\u1E72\u0172\u1E76\u1E74\u0244]/g},
        {'base':'V', 'letters':/[\u0056\u24CB\uFF36\u1E7C\u1E7E\u01B2\uA75E\u0245]/g},
        {'base':'W', 'letters':/[\u0057\u24CC\uFF37\u1E80\u1E82\u0174\u1E86\u1E84\u1E88\u2C72]/g},
        {'base':'X', 'letters':/[\u0058\u24CD\uFF38\u1E8A\u1E8C]/g},
        {'base':'Y', 'letters':/[\u0059\u24CE\uFF39\u1EF2\u00DD\u0176\u1EF8\u0232\u1E8E\u0178\u1EF6\u1EF4\u01B3\u024E\u1EFE]/g},
        {'base':'Z', 'letters':/[\u005A\u24CF\uFF3A\u0179\u1E90\u017B\u017D\u1E92\u1E94\u01B5\u0224\u2C7F\u2C6B\uA762]/g},

    ];

    for(var i=0; i<defaultDiacriticsRemovalMap.length; i++) {
        str = str.replace(defaultDiacriticsRemovalMap[i].letters, defaultDiacriticsRemovalMap[i].base);
    }

    return str;

}



export function matchStateToTerm (state, value) {

  return (
    removeDiacritics(state.label.toUpperCase()).indexOf(removeDiacritics(value.toUpperCase().trim())) !== -1
   // removeDiacritics(state.abbr.toLowerCase()).indexOf(removeDiacritics(value.toLowerCase())) !== -1
  )
}

export function sortStates (a, b, value) {
  console.log(a,b);

    if (a.label.toUpperCase() > b.label.toUpperCase()) {
        return 1;
    }
    if (a.label.toUpperCase() < b.label.toUpperCase()) {
        return -1;
    }

    return 0


}

export function fakeRequest (value, cb) {
  if (value === '')
    return getStates()
  var items = getStates().filter((state) => {
    return matchStateToTerm(state, value)
  })
  setTimeout(() => {
    cb(items)
  }, 500)
}

export function getStates() {
  var all = [
    { abbr: "AL", name: "Alabama"},
    { abbr: "AK", name: "Alaska"},
    { abbr: "AZ", name: "Arizona"},
    { abbr: "AR", name: "Arkansas"},
    { abbr: "CA", name: "California"},
    { abbr: "CO", name: "Colorado"},
    { abbr: "CT", name: "Connecticut"},
    { abbr: "DE", name: "Delaware"},
    { abbr: "FL", name: "Florida"},
    { abbr: "GA", name: "Georgia"},
    { abbr: "HI", name: "Hawaii"},
    { abbr: "ID", name: "Idaho"},
    { abbr: "IL", name: "Illinois"},
    { abbr: "IN", name: "Indiana"},
    { abbr: "IA", name: "Iowa"},
    { abbr: "KS", name: "Kansas"},
    { abbr: "KY", name: "Kentucky"},
    { abbr: "LA", name: "Louisiana"},
    { abbr: "ME", name: "Maine"},
    { abbr: "MD", name: "Maryland"},
    { abbr: "MA", name: "Massachusetts"},
    { abbr: "MI", name: "Michigan"},
    { abbr: "MN", name: "Minnesota"},
    { abbr: "MS", name: "Mississippi"},
    { abbr: "MO", name: "Missouri"},
    { abbr: "MT", name: "Montana"},
    { abbr: "NE", name: "Nebraska"},
    { abbr: "NV", name: "Nevada"},
    { abbr: "NH", name: "New Hampshire"},
    { abbr: "NJ", name: "New Jersey"},
    { abbr: "NM", name: "New Mexico"},
    { abbr: "NY", name: "New York"},
    { abbr: "NC", name: "North Carolina"},
    { abbr: "ND", name: "North Dakota"},
    { abbr: "OH", name: "Ohio"},
    { abbr: "OK", name: "Oklahoma"},
    { abbr: "OR", name: "Oregon"},
    { abbr: "PA", name: "Pennsylvania"},
    { abbr: "RI", name: "Rhode Island"},
    { abbr: "SC", name: "South Carolina"},
    { abbr: "SD", name: "South Dakota"},
    { abbr: "TN", name: "Tennessee"},
    { abbr: "TX", name: "Texas"},
    { abbr: "UT", name: "Utah"},
    { abbr: "VT", name: "Vermont"},
    { abbr: "VA", name: "Virginia"},
    { abbr: "WA", name: "Washington"},
    { abbr: "WV", name: "West Virginia"},
    { abbr: "WI", name: "Wisconsin"},
    { abbr: "WY", name: "Wyoming"}
  ];



    var data2 = [
        {
            "Ifac - Instituto Federal do Acre": 0,
            "Ufac - Universidade Federal do Acre": 0,
            "Uninorte - União Educacional do Norte": 0,
            "Iesacre - Instituição de Ensino Superior do Acre": 0,
            "Fadisi - Faculdade Diocesana São José": 0,
            "Faao - Faculdade da Amazônia Ocidental": 0,
            "Fameta - Faculdade Meta": 0,
            "Faeuc - Faculdade Euclides da Cunha": 0,
            "Uneal - Universidade Estadual de Alagoas": 0,
            "Uncisal - Universidade Estadual de Ciências da Saúde de Alagoas": 0,
            "Ifal - Instituto Federal de Alagoas": 0,
            "Ufal - Universidade Federal de Alagoas": 0,
            "Centro de Estudos Superiores de Maceió": 0,
            "Faculdade Integrada Tiradentes": 0,
            "Faculdade Pitágoras": 0,
            "Ueap - Universidade Estadual do Amapá": 0,
            "Ifap - Instituto Federal do Amapá": 0,
            "Unifap - Universidade Federal do Amapá": 0,
            "Centro de Ensino Superior do Amapá": 0,
            "Faculdade SEAMA": 0,
            "Faculdade FAMA": 0,
            "Faculdade Meta": 0,
            "IESAP": 0,
            "IMMES": 0,
            "Uea - Universidade do Estado do Amazonas": 0,
            "Ifam - Instituto Federal do Amazonas": 0,
            "Ufam - Universidade Federal do Amazonas": 0,
            "ULBRA - Universidade Luterana do Brasil": 0,
            "FSDB - Faculdade Salesiana Dom Bosco": 0,
            "Ciesa - Centro Universitário de Ensino Superior do Amazonas": 0,
            "Centro Universitário Nilton Lins": 0,
            "Cesf - Instituto de Ensino Superior Fucapi": 0,
            "FT - Faculdade Táhirih": 0,
            "Fametro - Faculdade Metropolitana de Manaus": 0,
            "FMF - Faculdade Martha Falcão": 0,
            "Fal - Faculdade Literatus": 0,
            "Unisalle - Faculdade La Salle": 0,
            "Iaes - Faculdade do Amazonas": 0,
            "Fom - Faculdade de Odontologia de Manaus": 0,
            "FBNCTSB - Faculdade Boas Novas de Ciências Teológicas": 0,
            "Esbam - Escola Superior Batista do Amazonas": 0,
            "Uninorte - Centro Universitário do Norte": 0,
            "Unip - Universidade Paulista": 0,
            "Uece - Universidade Estadual do Ceará": 0,
            "Urca - Universidade Regional do Cariri": 0,
            "Uva - Universidade Estadual Vale do Acaraú": 0,
            "Ifce - Instituto Federal do Ceará": 0,
            "UFC - Universidade Federal do Ceará": 0,
            "Unilab - Universidade Federal de Integração Luso-Afro-Brasileira": 0,
            "UFCA - Universidade Federal do Cariri": 0,
            "Unifor - Universidade de Fortaleza": 0,
            "Faculdade de Tecnologia Centec":0,
            "FCRS - Faculdade Católica Rainha do Sertão": 0,
            "FCC - Faculdade Católica do Ceará": 0,
            "FCF - Faculdade Católica de Fortaleza [1]": 0,
            "Fametro - Faculdade Metropolitana de Fortaleza": 0,
            "Ista - Instituto Superior de Teologia Aplicada": 0,
            "Fanor - Faculdades Nordeste": 0,
            "Faculdade Christus": 0,
            "Fac - Faculdades Cearenses": 0,
            "Face - Faculdade Evolutivo": 0,
            "Fals - Faculdade de Ciências Aplicadas Doutor Leão Sampaio": 0,
            "Fap - Faculdade Paraíso do Ceará": 0,
            "Fa7 - Faculdade 7 de Setembro": 0,
            "FFB - Faculdade Farias Brito": 0,
            "Fic - Faculdade Integrada do Ceará": 0,
            "FJN - Faculdade de Juazeiro do Norte": 0,
            "FLF - Faculdade Luciano Feijão": 0,
            "FMJ - Faculdade de Medicina de Juazeiro do Norte": 0,
            "FTA - Faculdade de Tecnologia Apoena": 0,
            "FVJ - Faculdade Vale do Jaguaribe": 0,
            "FGF - Faculdade Integrada da Grande Fortaleza": 0,
            "IFB - Instituto Federal de Brasília": 0,
            "UnB - Universidade de Brasília": 0,
            "ESCS - Escola Superior de Ciências da Saúde": 0,
            "UCB - Universidade Católica de Brasília": 0,
            "CEUB - Centro Universitário de Brasília": 0,
            "FATE - Faculdade Ateneu": 0,
            "FACIPLAC - Faculdade de Ciência e Tecnologia do Planalto Central": 0,
            "FACITEC - Faculdade de Ciências Sociais e Tecnológicas": 0,
            "FASEP - Faculdade Serrana": 0,
            "IESB - Instituto de Educação Superior de Brasília": 0,
            "UNIP - Universidade Paulista": 0,
            "UNIDESC - Centro Universitário de Desenvolvimento do Centro Oeste": 0,
            "UNIPLAN - Centro Universitário Planalto do Distrito Federal": 0,
            "UDF - Centro Universitário do Distrito Federal": 0,
            "UPIS - Faculdades Integradas": 0,
            "IFES - Instituto Federal do Espírito Santo": 0,
            "UFES - Universidade Federal do Espírito Santo": 0,
            "EMESCAM - Escola Superior de Ciências da Santa Casa de Misericórdia de Vitória": 0,
            "UVV - Universidade Vila Velha": 0,
            "UNESC - Centro Universitário do Espírito Santo": 0,
            "FAESA - Faculdades Integradas Espírito-Santenses": 0,
            "UCL - Faculdade do Centro Leste": 0,
            "Favi/FACES - Faculdade do Espírito Santo": 0,
            "ESFA- Escola Superior São Francisco de Assis": 0,
            "CUSC- Centro Universitário São Camilo": 0,
            "FAFIA- Faculdade de Filosofia Ciências e Letras de Alegre": 0,
            "FCB - [Faculdade Castelo Branco] Colatina/ES.": 0,
            "CESV - Centro de Ensino Superior de Vitória": 0,
            "FABAVI - Faculdade Batista de Vitoria": 0,
            "FDV - Faculdades Integradas de Vitória": 0,
            "FUCAPE - Fundação Instituto Capixaba de Pesquisas em Contabilidade":0,
            "UNESA - Universidade Estácio de Sá": 0,
            "CESAT- Escola de Ensino Superior Anísio Teixeira": 0,
            "FASE- Faculdade da Serra": 0,
            "MULTIVIX- Faculdade Brasileira": 0,
            "PIO XII- Faculdade de Estudos Sociais do Espírito Santo": 0,
            "SABERES- Faculdade Saberes": 0,
            "FCMV- Faculdade Candido Mendes de Vitória": 0,
            "FAACZ - Faculdade de Aracruz": 0,
            "FACE - Faculdade Casa do Estudante": 0,
            "UniRV - Universidade de Rio Verde -www.unirv.edu.br/": 0,
            "UEG - Universidade Estadual de Goiás": 0,
            "IFG - Instituto Federal de Goiás": 0,
            "UFG - Universidade Federal de Goiás": 0,
            "IF Goiano - Instituto Federal Goiano": 0,
            "IPOG- Instituto de Pós-Graduação": 0,
            "PUC - Pontifícia Universidade Católica de Goiás": 0,
            "UNIVERSO - Universidade Salgado de Oliveira": 0,
            "Fac- Faculdade Católica de Anápolis": 0,
            "ALFA - Faculdade Alves Faria": 0,
            "CESUC - Centro de Ensino Superior de Catalão": 0,
            "FACERES - Faculdade de Ceres": 0,
            "FACER - Faculdade de Ciências de Rubiataba": 0,
            "FACEG -Faculdade Evangelica de Goianesia": 0,
            "FAA - Faculdade Anhanguera de Anápolis": 0,
            "FASAM - Faculdade Sul-Americana": 0,
            "FESURV - Universidade de Rio Verde[4]": 0,
            "INSJAR - Instituto Jordão de Arruda": 0,
            "UNIFASC - Faculdade Santa Rita de Cássia": 0,
            "UniEvangelica- Universidade Evangelica": 0,
            "Unianhanguera- Universidade Anhanguera": 0,
            "IAESUP- Faculdades e Colégio Aphonsiano": 0,
            "IUESO- Faculdades Objetivo": 0,
            "FMB- Faculdade Montes Belos": 0,
            "UEMA - Universidade Estadual do Maranhão": 0,
            "UNIVIMA - Universidade Virtual do Maranhão": 0,
            "IFMA - Instituto Federal do Maranhão": 0,
            "UFMA - Universidade Federal do Maranhão": 0,
            "CEST - Faculdade Santa Terezinha (São Luís)": 0,
            "FACIMP - Faculdade de Imperatriz": 0,
            "FEST - Faculdade Santa Terezinha (Imperatriz)": 0,
            "FSL - Faculdade São Luís": 0,
            "FACEMA - Faculdade de Ciências e Tecnologia do Maranhão (Caxias)": 0,
            "UNDB - Unidade de Ensino Superior Dom Bosco (São Luís)": 0,
            "UNICEUMA - Centro Universitário do Maranhão (São Luís)": 0,
            "FAMA - Faculdade Atenas Maranhense": 0,
            "FAP - Faculdade do Baixo Paranaíba (Chapadinha)": 0,
            "UNEMAT - Universidade do Estado de Mato Grosso": 0,
            "IFMT - Instituto Federal do Mato Grosso": 0,
            "UFMT - Universidade Federal de Mato Grosso": 0,
            "FADAF - Faculdade de Direito de Alta Floresta": 0,
            "ULBRA - Universidade Luterana do Brasil - EAD": 0,
            "Anhanguera - Faculdade Anhanguera": 0,
            "EDUVALE - Faculdade de Ciências Sociais Aplicadas do Vale do São Lourenço": 0,
            "UNIC - Universidade de Cuiabá": 0,
            "FASIPE - Faculdade de Sinop": 0,
            "UNIRONDON - Centro Universitário Cândido Rondon": 0,
            "UNIVAG - Centro Universitário de Várzea Grande": 0,
            "UNIVAR - Universidades Unidas do Vale do Araguaia-Barra do Garças": 0,
            "CATHEDRAL - Faculdades Cathedral-Barra do Garças": 0,
            "UEMS - Universidade Estadual do Mato Grosso do Sul": 0,
            "UFGD - Universidade Federal da Grande Dourados": 0,
            "IFMS - Instituto Federal de Mato Grosso do Sul": 0,
            "UFMS - Universidade Federal do Mato Grosso do Sul": 0,
            "UFPAN - Universidade Federal do Pantanal": 0,
            "UCDB - Universidade Católica Dom Bosco": 0,
            "AEMS - Faculdades Integradas de Três Lagoas": 0,
            "UNAES - Centro Universitário de Campo Grande": 0,
            "UNIDERP - Universidade para o Desenvolvimento do Estado e Região do Pantanal": 0,
            "UNIGRAN - Centro Universitário da Grande Dourados": 0,
            "FCG- Faculdade Campo Grande": 0,
            "FACSUL -Faculdade Mato Grosso do Sul": 0,
            "FJP - Fundação João Pinheiro": 0,
            "UEMG - Universidade do Estado de Minas Gerais": 0,
            "UNIMONTES - Universidade Estadual de Montes Claros": 0,
            "CEFET-MG - Centro Federal de Educação Tecnológica de Minas Gerais": 0,
            "IFMG - Instituto Federal de Minas Gerais": 0,
            "IFNM - Instituto Federal do Norte de Minas": 0,
            "IFSM - Instituto Federal do Sudeste de Minas": 0,
            "IFSUM - Instituto Federal do Sul de Minas": 0,
            "IFTM - Instituto Federal do Triângulo Mineiro": 0,
            "UFJF - Universidade Federal de Juiz de Fora": 0,
            "UFLA - Universidade Federal de Lavras": 0,
            "UFMG - Universidade Federal de Minas Gerais": 0,
            "UFOP - Universidade Federal de Ouro Preto": 0,
            "UFSJ - Universidade Federal de São João del-Rei": 0,
            "UFTM - Universidade Federal do Triângulo Mineiro": 0,
            "UFU - Universidade Federal de Uberlândia": 0,
            "UFV - Universidade Federal de Viçosa": 0,
            "UFVJM - Universidade Federal dos Vales do Jequitinhonha e Mucuri": 0,
            "UNIFAL - Universidade Federal de Alfenas": 0,
            "UNIFEI - Universidade Federal de Itajubá": 0,
            "Academia de Polícia Militar de Minas Gerais": 0,
            "EEK - Escola de Engenharia Kennedy": 0,
            "EEWB - Escola de Enfermagem Wenceslau Braz": 0,
            "ESDHC - Escola Superior Dom Helder Câmara": 0,
            "FACAPA - (Faculdade Católica de Pouso Alegre)": 0,
            "FADMINAS - Faculdades Integradas Adventistas de Minas Gerais": 0,
            "FAGAMMON - Faculdade Presbiteriana Gammon": 0,
            "FESP - Fundação de Ensino Superior de Passos": 0,
            "FDSM - Faculdade de Direito do Sul de Minas": 0,
            "FACECA - Faculdade Cenecista de Varginha": 0,
            "FASF - Unisa - Faculdade de Filosofia": 0,
            "FAVALE-UEMG- Faculdades Vale do Carangola": 0,
            "FAZU - Faculdades Associadas de Uberaba": 0,
            "FCMMG - Faculdade de Ciências Médicas de Minas Gerais": 0,
            "FCMS/JF - Faculdade de Ciências Médicas e da Saúde de Juiz de Fora": 0,
            "FMG - Faculdade Metodista Granbery": 0,
            "FMIT - Faculdade de Medicina de Itajubá": 0,
            "FUNJOB - Faculdade de Medicina de Barbacena": 0,
            "FUMEC - Fundação Mineira de Educação e Cultura": 0,
            "FUNCESI - Fundação Comunitária de Ensino Superior de Itabira": 0,
            "IESP - Instituto de Educação Superior de Patrocínio": 0,
            "PUCMG - Pontifícia Universidade Católica de Minas Gerais": 0,
            "UIT - Universidade de Itaúna": 0,
            "UNIARAXÁ - Centro Universitário do Planalto de Araxá": 0,
            "UNIBH - Centro Universitário de Belo Horizonte": 0,
            "UNICERP - Centro Universitário do Cerrado - Patrocínio": 0,
            "UNIFEMM - Centro Universitário de Sete Lagoas": 0,
            "UNIFORMG - Centro Universitário de Formiga": 0,
            "UNILESTE/MG - Centro Universitário do Leste de Minas Gerais": 0,
            "UNIPAC - Universidade Presidente Antônio Carlos": 0,
            "UNIPAM - Centro Universitário de Patos de Minas": 0,
            "UNITRI - Centro Universitário do Triângulo": 0,
            "UNIUBE - Universidade de Uberaba": 0,
            "UNIVAS - Universidade do Vale do Sapucaí": 0,
            "UNIVALE - Universidade Vale do Rio Doce": 0,
            "ASMEC - Associação Sul Mineira de Educação e Cultura": 0,
            "CECON - Centro Educacional Conceição Nunes": 0,
            "CENSI - Centro de Ensino Superior de Itabira": 0,
            "FACESM - Faculdade de Ciências Sociais Aplicadas do Sul de Minas": 0,
            "FACICA - Faculdade de Ciências da Saúde de Campos Gerais": 0,
            "FACED - Faculdade de Ciências Contabeis de Divinópolis": 0,
            "FACTU - Faculdade de Ciências e Tecnologia de Unaí": 0,
            "FEAD - Faculdade de Estudos Administrativos de Minas Gerais": 0,
            "FADOM - Faculdades integradas do Oeste de Minas": 0,
            "FAVENORTE - Instituto Superior de Educação Verde Norte": 0,
            "FEMG - Faculdade de Engenharia de Minas Gerais": 0,
            "FMC - Faculdades Milton Campos": 0,
            "FPAS - Faculdade Pitágoras de Administração Superior": 0,
            "FPMG - Faculdade Promove de Minas Gerais": 0,
            "FPU - Faculdade Politécnica de Uberlândia": 0,
            "FSA - Faculdades Santo Agostinho": 0,
            "FUNEDI - Fundação Educacional de Divinópolis": 0,
            "SECAL - Faculdade Santa Amélia": 0,
            "INESC - Instituto de Ensino Superior Cenecista": 0,
            "IPTAN - Instituto de Ensino Superior Presidente Tancredo Neves": 0,
            "ISEC - Instituto Superior de Educação de Campos Gerais": 0,
            "UNA - Centro Universitário UNA": 0,
            "UNIFENAS - Universidade de Alfenas": 0,
            "UNILAVRAS - Centro Universitário de Lavras": 0,
            "UNIVERSITAS - Centro Universitário de Itajubá": 0,
            "UNIVIÇOSA - União de Ensino Superior de Viçosa - Univiçosa": 0,
            "IFPA - Instituto Federal do Pará": 0,
            "UFPA - Universidade Federal do Pará": 0,
            "UFOPA - Universidade Federal do Oeste do Pará": 0,
            "UFRA - Universidade Federal Rural da Amazônia": 0,
            "UNIFESSPA - Universidade Federal do Sul e Sudeste do Pará": 0,
            "UEPA - Universidade do Estado do Pará": 0,
            "CIABA - Centro de Instrução Almirante Braz de Aguiar": 0,
            "CEAMA - Centro de Educação da Amazônia": 0,
            "CESUPA - Centro Universitário do Pará": 0,
            "ESMAC - Escola Superior Madre Celeste": 0,
            "ESAMAZ - Escola Superior da Amazônia": 0,
            "ESTÁCIO FAP - Estácio de Sá - Faculdade do Pará": 0,
            "FAAMA - Faculdade Adventista da Amazônia": 0,
            "FAAM - Faculdade da Amazônia": 0,
            "FAMAZ - Faculdade Metropolitana da Amazônia": 0,
            "FABEL - Faculdade de Belém": 0,
            "FACETE - Faculdade de Ensino Tecnológico do Estado do Pará": 0,
            "FACI - Faculdade Ideal": 0,
            "FACIP - Faculdade Ipiranga": 0,
            "FAPAN - Faculdade Pan Amazônica": 0,
            "FCAT - Faculdade de Castanhal": 0,
            "FEAPA - Faculdade de Estudos Avançados do Pará": 0,
            "FIT - Faculdades Integradas do Tapajós - FIT (Santarém)": 0,
            "FIBRA - Faculdade Integrada Brasil Amazônia": 0,
            "FMM - Faculdade Metropolitana de Marabá": 0,
            "FPA - Faculdade Pan Americana": 0,
            "IESAM - Instituto de Ensinos Superiores da Amazônia": 0,
            "UNAMA - Universidade da Amazônia": 0,
            "UEPB - Universidade Estadual da Paraíba": 0,
            "IFPB - Instituto Federal da Paraíba": 0,
            "UFPB - Universidade Federal da Paraíba": 0,
            "UFCG - Universidade Federal de Campina Grande": 0,
            "UNIPÊ - Centro Universitário de João Pessoa": 0,
            "FPB - Faculdade Internacional da Paraíba": 0,
            "LUMEN FAC - Faculdade de Ciências Contábeis Luiz Mendes": 0,
            "LUMEN FAC - Faculdade de Ciências Médicas da Paraíba": 0,
            "FACENE - Faculdade de Enfermagem Nova Esperança": 0,
            "FESVIP - Faculdade de Enfermagem São Vicente de Paula": 0,
            "FESP - Faculdade de Ensino Superior da Paraíba": 0,
            "FAESNE - Faculdade de Ensino Superior do Nordeste": 0,
            "DEVRY - DeVry João Pessoa": 0,
            "FATEC - Faculdade de Tecnologia de João Pessoa": 0,
            "UNIUOL - Faculdade de Tecnologia do Uniuol": 0,
            "UNIBRATEC - Faculdade de Tecnologia Ibratec": 0,
            "ESBJ - Faculdade Maurício de Nassau": 0,
            "FAP - Faculdade Paraibana": 0,
            "FPPD - Faculdade Paraibana de Processamento de Dados": 0,
            "FPB - Faculdade Potiguar da Paraíba": 0,
            "FASER - Faculdade Santa Emília de Rodat": 0,
            "UNIPB - Faculdade Unida da Paraíba": 0,
            "FIAA - Faculdades Integradas Anglo - Americano": 0,
            "INPER - Insituto Paraibano de Ensino Renovado": 0,
            "IPOG - Instituto de Pós-Graduação & Graduação": 0,
            "FATECPB - Faculdade de Tecnología da Paraíba": 0,
            "IESP - Instituto de Educação Superior da Paraíba": 0,
            "FAFIC - Faculdade de Filosofía Ciências e Letras de Cajazeiras": 0,
            "FEF - Faculdade Evilásio Formiga": 0,
            "FSM - Faculdade Santa María": 0,
            "FASP - Faculdade São Francisco da Paraíba": 0,
            "ISEC - Insituto Superior de Educação de Cajazeiras": 0,
            "ESAC - Escola Superior de Aviação Civil": 0,
            "FAC - Faculdade de Campina Grande": 0,
            "FCM - Faculdade de Ciências Médicas de Campina Grande": 0,
            "FARR - Faculdade Reinaldo Ramos": 0,
            "FAFIL - Faculdade de Filosofía Ciências e Letras": 0,
            "FIP - Faculdades Integradas de Patos": 0,
            "UNESPAR - Universidade Estadual do Paraná": 0,
            "UEL - Universidade Estadual de Londrina": 0,
            "UEM - Universidade Estadual de Maringá": 0,
            "UENP - Universidade Estadual do Norte do Paraná": 0,
            "UEPG - Universidade Estadual de Ponta Grossa": 0,
            "UNICENTRO - Universidade Estadual do Centro-Oeste": 0,
            "UNIOESTE - Universidade Estadual do Oeste do Paraná": 0,
            "UTFPR - Universidade Tecnológica Federal do Paraná": 0,
            "UFPR - Universidade Federal do Paraná": 0,
            "UNILA - Universidade Federal da Integração Latino-Americana": 0,
            "UFFS - Universidade Federal da Fronteira do Sul": 0,
            "FAE - FAE Centro Universitário[6]": 0,
            "FAG - Fundação Assis Gurgacz": 0,
            "FEPAR - Faculdade Evangélica do Paraná[7]": 0,
            "FPP - Faculdades Pequeno Príncipe": 0,
            "PUCPR - Pontifícia Universidade Católica do Paraná": 0,
            "UNIFIL - Centro Universitário Filadélfia[8]": 0,
            "Univel - União Educacional de Cascavel": 0,
            "UNINGÁ - Faculdade Ingá": 0,
            "CESCAGE - Centro de Ensino Superior dos Campos Gerais": 0,
            "CESUMAR - Centro Universitário de Maringá": 0,
            "FAJAR - Faculdade Jaguariaíva": 0,
            "FATEB - Faculdade de Telêmaco Borba": 0,
            "FANP - Faculdade do Noroeste Paranaense": 0,
            "FAPI - Faculdades de Pinhais": 0,
            "FASF - Faculdade Sagrada Família": 0,
            "FARESC - Faculdades Integradas Santa Cruz de Curitiba": 0,
            "FESC - Fundação de Ensino Superior de Clevelândia": 0,
            "FIES - Faculdades Integradas Espírita": 0,
            "FML - Faculdade Metropolitana Londrinense": 0,
            "UEB - Universidade Eletrônica do Brasil": 0,
            "UNIANDRADE - Centro Universitário Campos de Andrade": 0,
            "UNICAMPO - Faculdade União de Campo Mourão[9]": 0,
            "UNICURITIBA - Centro Universitário Curitiba": 0,
            "UNINTER - Grupo Educacional Uninter": 0,
            "UNIPAR - Universidade Paranaense": 0,
            "UNOPAR - Universidade do Norte do Paraná": 0,
            "UCP - Faculdades do Centro do Paraná": 0,
            "UP - Universidade Positivo": 0,
            "UTP - Universidade Tuiuti do Paraná": 0,
            "FAAB - Faculdade Alfa Brasil": 0,
            "UNISEP - União de Ensino do Sudoeste do Paraná [10]": 0,
            "Faculdade Campo Real": 0,
            "Faculdade Guairacá": 0,
            "Faculdade Guarapuava": 0,
            "UFPI - Universidade Federal do Piauí": 0,
            "IFPI - Instituto Federal do Piauí": 0,
            "UESPI - Universidade Estadual do Piauí": 0,
            "ISEAF - Instituto Superior de Educação Antonino Freire": 0,
            "Novafapi - Faculdade de Saúde": 0,
            "CEUT - Centro de Ensino Unificado de Teresina": 0,
            "ALIANÇA - Faculdade Aliança": 0,
            "FSA - Faculdade Santo Agostinho": 0,
            "FACID - Faculdade Integral Diferencial": 0,
            "CET - Centro de Educação Tecnológico": 0,
            "ICF - Instituto Camillo Filho": 0,
            "FAP - Faculdade Piauiense": 0,
            "IERSA - Instituto Educacional Raimundo Sá (Faculdade R. Sá)": 0,
            "FeMASS - Faculdade Professor Miguel Ângelo da Silva Santos - Macaé": 0,
            "FAETERJ - Faculdade de Educação Tecnológica do Estado do Rio de Janeiro": 0,
            "UENF - Universidade Estadual do Norte Fluminense": 0,
            "UERJ - Universidade do Estado do Rio de Janeiro": 0,
            "UEZO - Universidade Estadual da Zona Oeste": 0,
            "IFF - Instituto Federal Fluminense": 0,
            "IFRJ - Instituto Federal do Rio de Janeiro": 0,
            "CEFET/RJ - Centro Federal de Educação Tecnológica Celso Suckow da Fonseca": 0,
            "ENCE - Escola Nacional de Ciências Estatísticas": 0,
            "UFF - Universidade Federal Fluminense": 0,
            "UFRJ - Universidade Federal do Rio de Janeiro": 0,
            "UFRRJ - Universidade Federal Rural do Rio de Janeiro": 0,
            "UNIRIO - Universidade Federal do Estado do Rio de Janeiro": 0,
            "AMAN - Academia Militar de Agulhas Negras": 0,
            "APMDJVI - Academia de Polícia Militar Dom João VI": 0,
            "CIAGA - Centro de Instrução Almirante Graça Aranha": 0,
            "EN - Escola Naval": 0,
            "IME - Instituto Militar de Engenharia": 0,
            "FIJ - Faculdades Integradas de Jacarepaguá": 0,
            "FACHA - Faculdades Integradas Hélio Alonso": 0,
            "FFSD - Faculdade de Filosofia Santa Doroteia": 0,
            "FMC - Faculdade de Medicina de Campos": 0,
            "FSMA - Faculdade Salesiana de Macaé": 0,
            "FTESM- Fundação Técnico Educacional Souza Marques": 0,
            "Mackenzie Rio -Faculdade Presbiteriana Mackenzie RJ": 0,
            "PUCRIO - Pontifícia Universidade Católica do Rio de Janeiro": 0,
            "FSB/RJ - Faculdade de São Bento do Rio de Janeiro": 0,
            "UCAM - Universidade Cândido Mendes": 0,
            "BENNETT - Instituto Metodista BENNETT": 0,
            "IBMR - Centro Universitário Hermínio da Silveira": 0,
            "UCB - Universidade Castelo Branco": 0,
            "UCP - Universidade Católica de Petrópolis": 0,
            "UGB - Centro Universitário Geraldo Di Biase": 0,
            "UGS - Universidade Gama e Souza": 0,
            "UNISUAM - Centro Universitário Augusto Motta": 0,
            "UNIABEU Centro Universitário": 0,
            "UNICARIOCA - Centro Universitário Carioca": 0,
            "UNIGRANRIO - Universidade do Grande Rio": 0,
            "UNIVERCIDADE - Centro Universitário da Cidade do Rio de Janeiro": 0,
            "USS - Universidade Severino Sombra": 0,
            "USU - Universidade Santa Úrsula": 0,
            "UVA - Universidade Veiga de Almeida": 0,
            "REDENTOR - Sociedade Universitária Redentor - Faculdade Redentor": 0,
            "FGV - Fundação Getúlio Vargas": 0,
            "INFNET - Instituto Infnet[3]": 0,
            "UBM - Centro Universitário de Barra Mansa": 0,
            "UNIFOA - Centro Universitário de Volta Redonda": 0,
            "Laboratório Central de Petróleo e Gás Natural da Universidade Federal do Rio Grande do Norte.": 0,
            "UERN - Universidade do Estado do Rio Grande do Norte": 0,
            "IFRN - Instituto Federal do Rio Grande do Norte": 0,
            "UFERSA - Universidade Federal Rural do Semi-Árido": 0,
            "UFRN - Universidade Federal do Rio Grande do Norte": 0,
            "ULBRA - Universidade Luterana do Brasil (Polo Natal)": 0,
            "UNP - Universidade Potiguar": 0,
            "FARN - Faculdade Natalense para o Desenvolvimento do Rio Grande do Norte": 0,
            "Fatern Gama Filho - Faculdade de Excelência do Rio Grande do Norte": 0,
            "FAL - Faculdade de Natal": 0,
            "Facex - Faculdade de Ciências": 0,
            "FCC - Faculdade Câmara Cascudo": 0,
            "Fanec - Faculdade Natalense de Ensino e Cultura": 0,
            "Faculdade Católica Nossa Senhora Das Neves": 0,
            "Faculdade Maurício de Nassau - (Pólo Natal)": 0,
            "IPOG - Instituto de Pós-Graduação (Pólo Natal)": 0,
            "Facene/RN - Faculdade de Enfermagem e Medicina Nova Esperança de Mossoró": 0,
            "Faculdade Mater Christi": 0,
            "Rio Grande do Sul[editar | editar código-fonte]": 0,
            "UERGS - Universidade Estadual do Rio Grande do Sul": 0,
            "FURG - Universidade Federal do Rio Grande": 0,
            "IFFarroupilha - Instituto Federal Farroupilha": 0,
            "IFRS - Instituto Federal do Rio Grande do Sul": 0,
            "IFSul - Instituto Federal Sul-rio-grandense": 0,
            "UFCSPA - Universidade Federal de Ciências da Saúde de Porto Alegre": 0,
            "UFPEL - Universidade Federal de Pelotas": 0,
            "UFRGS - Universidade Federal do Rio Grande do Sul": 0,
            "UFSM - Universidade Federal de Santa Maria": 0,
            "UNIPAMPA - Universidade Federal do Pampa": 0,
            "FACCAT - Faculdades Integradas de Taquara": 0,
            "FACOS - Faculdade Cenecista de Osório": 0,
            "FISMA - Faculdade Integrada de Santa Maria": 0,
            "FAPA - Faculdade Porto Algrense": 0,
            "FEEVALE - Universidade Feevale": 0,
            "FACENSA - Faculdade Cenecista Nossa Senhora dos Anjos": 0,
            "IACS - Instituto Adventista Cruzeiro do Sul": 0,
            "MARQUÊS - Instituto de Educação Cenecista Marquês de Herval": 0,
            "IESA - Instituto Cenecista de Ensino Superior de Santo Ângelo": 0,
            "IPA - Centro Universitário Metodista do Instituto Porto Alegre": 0,
            "PUCRS - Pontifícia Universidade Católica do Rio Grande do Sul": 0,
            "UCPEL - Universidade Católica de Pelotas": 0,
            "UCS - Universidade de Caxias do Sul": 0,
            "UNICRUZ - Universidade de Cruz Alta": 0,
            "UNIFRA - Centro Universitário Franciscano": 0,
            "UNIJUÍ - Universidade Regional do Noroeste do Estado do Rio Grande do Sul": 0,
            "UNIRITTER - Centro Universitário Ritter dos Reis": 0,
            "UNILASALLE - Centro Universitário La Salle": 0,
            "UNILASALLE-RJ - Centro Universitário La Salle": 0,
            "UNISC - Universidade de Santa Cruz do Sul": 0,
            "UNISINOS - Universidade do Vale do Rio dos Sinos": 0,
            "UNIVATES - Centro Universitário UNIVATES": 0,
            "UPF - Universidade de Passo Fundo": 0,
            "URCAMP - Universidade da Região da Campanha": 0,
            "URI - Universidade Regional Integrada do Alto Uruguai e das Missões": 0,
            "EST - Faculdades EST": 0,
            "CESF - Centro de Ensino Superior Cenecista de Farroupilha": 0,
            "ESMARGS - Escola Superior de Música e Artes do Rio Grande do Sul": 0,
            "FAM - Faculdade Antonio Meneghetti": 0,
            "FAACS - Faculdade Anglo-Americano de Caxias do Sul": 0,
            "FSG - Faculdade da Serra Gaúcha": 0,
            "FTEC - Faculdade de Tecnologia TecBrasil": 0,
            "SJT - Instituição Educacional São Judas Tadeu": 0,
            "UNIANHANGUERA - Anhanguera Educacional S.A.": 0,
            "FEMA - Escola Técnica e Superior Machado de Assis - Santa Rosa": 0,
            "FADISMA - Faculdade de Direito de Santa Maria": 0,
            "CASTELLI - Escola Superior de Hotelaria Castelli": 0,
            "FAE - Faculdade Anglicana de Erechim": 0,
            "UNIR - Universidade Federal de Rondônia": 0,
            "IFRO - Instituto Federal de Rondônia": 0,
            "AVEC - Associação Vilhenense de Educação e Cultura": 0,
            "CEULJI/ULBRA - Centro Universitário Luterano de Ji-Paraná": 0,
            "ILES/ULBRA - Instituto Luterano de Ensino Superior de Porto Velho": 0,
            "FAMA - Faculdade da Amazônia": 0,
            "FAEV/UNESC - Faculdade de Educação e Cultura de Vilhena": 0,
            "FARO - Faculdade de Ciências Humanas": 0,
            "UNIRON - Faculdade Interamericana de Porto Velho": 0,
            "FIMCA - Faculdades Integradas Aparício Carvalho": 0,
            "FSL - Faculdade São Lucas": 0,
            "FIAR - Faculdades Integradas de Ariquemes": 0,
            "FAAR - Faculdades Associadas de Ariquemes": 0,
            "FAEMA - Faculdade de Educação e Meio Ambiente": 0,
            "FACIMED - Faculdade de Ciências Biomédicas de Cacoal": 0,
            "UNESC - Faculdades Integradas de Cacoal": 0,
            "UNIJIPA -Faculdade Panamericana de Ji-Paraná": 0,
            "CLARETIANO - centro universitário": 0,
            "Funorte - Faculdades Unidas do Norte de Minas": 0,
            "UERR - Universidade Estadual de Roraima": 0,
            "UFRR - Universidade Federal de Roraima": 0,
            "IFRR - Instituto Federal de Roraima": 0,
            "FACETEN - Faculdade de Ciências": 0,
            "Faculdades Cathedral": 0,
            "FARES - Faculdade Roraimense de Ensino Superior": 0,
            "UDESC - Universidade do Estado de Santa Catarina": 0,
            "UFFS - Universidade Federal da Fronteira Sul": 0,
            "Instituto Federal de Santa Catarina": 0,
            "Instituto Federal Catarinense": 0,
            "UFSC - Universidade Federal de Santa Catarina": 0,
            "FURB - Fundação Universidade Regional de Blumenau": 0,
            "SOCIESC - Sociedade Educacional de Santa Catarina": 0,
            "UNESC - Universidade do Extremo Sul Catarinense": 0,
            "USJ - Universidade Municipal de São José": 0,
            "UNOESC - Universidade do Oeste de Santa Catarina": 0,
            "UNIASSELVI- Centro Universitário Leonardo da Vinci": 0,
            "UNIBAVE - Universidade Barriga Verde": 0,
            "UNIFEBE - Centro Universitário de Brusque": 0,
            "UNISUL - Universidade do Sul de Santa Catarina": 0,
            "UNC - Universidade do Contestado": 0,
            "UNIARP - Universidade Alto Vale do Rio do Peixe": 0,
            "UNERJ - Centro Universitário de Jaraguá do Sul": 0,
            "UNIVALI - Universidade do Vale do Itajaí": 0,
            "UNIVILLE - Universidade da Região de Joinville": 0,
            "UNOCHAPECÓ - Universidade Comunitária Regional de Chapecó": 0,
            "UNIPLAC - Universidade do Planalto Catarinense": 0,
            "ACE - Associação Catarinense de Ensino": 0,
            "FACC - Faculdade Concórdia": 0,
            "FAACH - Faculdade Santa Rita de Chapecó": 0,
            "FAP - Faculdade Santa Rita Palmitos": 0,
            "Escola de Artes": 0,
            "USP - Universidade de São Paulo": 0,
            "UNICAMP - Universidade Estadual de Campinas": 0,
            "UNESP - Universidade Estadual Paulista": 0,
            "Univesp - Universidade Virtual do Estado de São Paulo": 0,
            "FAMEMA - Faculdade de Medicina de Marília": 0,
            "FAMERP - Faculdade de Medicina de São José do Rio Preto": 0,
            "FATEC - Faculdade de Tecnologia do Estado de São Paulo": 0,
            "APMBB - Academia de Polícia Militar do Barro Branco": 0,
            "UNIFESP - Universidade Federal de São Paulo": 0,
            "UFSCAR - Universidade Federal de São Carlos": 0,
            "UFABC - Universidade Federal do ABC": 0,
            "IFSP - Instituto Federal de Educação": 0,
            "ITA - Instituto Tecnológico de Aeronáutica": 0,
            "AFA - Academia da Força Aérea": 0,
            "UNITAU - Universidade de Taubaté": 0,
            "USCS - Universidade Municipal de São Caetano do Sul": 0,
            "Centros Universitários": 0,
            "UNIFAE - Centro Universitário das Faculdades Associadas de Ensino": 0,
            "Uni-FACEF - Centro Universitário de Franca": 0,
            "CUFSA - Centro Universitário Fundação Santo André[13]": 0,
            "Faculdades e Institutos": 0,
            "FACCAMP - Faculdade de Campo Limpo Paulista": 0,
            "EEP/FUMEP - Escola de Engenharia de Piracicaba[14]": 0,
            "ESEFIC - Escola Superior de Cruzeiro": 0,
            "ESEFJ - Escola Superior de Educação Física de Jundiaí": 0,
            "FITO - Fundação Instituto Tecnológico de Osasco": 0,
            "FATEB - Faculdade de Ciências e Tecnologia de Birigui": 0,
            "FDF - Faculdade de Direito de Franca": 0,
            "FDSBC - Faculdade de Direito de São Bernardo do Campo": 0,
            "FAIBI - Faculdade de Filosofia": 0,
            "FFCL - Faculdade de Filosofia Ciências e Letras de São José do Rio Pardo": 0,
            "FMABC - Faculdade de Medicina do ABC": 0,
            "FMJ - Faculdade de Medicina de Jundiaí": 0,
            "FMPFM - Faculdade Municipal Professor Franco Montoro de Mogi Guaçu": 0,
            "FAI - Faculdades Adamantinenses Integradas": 0,
            "FAFEM - Faculdades da Fundação de Ensino de Mococa": 0,
            "FUNEC - Faculdades Integradas de Santa Fé do Sul": 0,
            "IESF - Instituto de Ensino Superior da Fupesp": 0,
            "IMMES - Instituto Matonense Municipal de Ensino Superior": 0,
            "IMESB - Instituto Municipal de Ensino Superior de Bebedouro Victório Cardassi": 0,
            "IMES Catanduva - Instituto Municipal de Ensino Superior de Catanduva": 0,
            "IMESSM - Instituto Municipal de Ensino Superior de São Manuel": 0,
            "IMESA - Instituto Municipal de Ensino Superior de Assis": 0,
            "FEA - Fundação Educacional Araçatuba": 0,
            "MACK - Universidade Presbiteriana Mackenzie": 0,
            "PUCSP - Pontifícia Universidade Católica de São Paulo": 0,
            "PUC-Campinas - Pontifícia Universidade Católica de Campinas":0,
            "UMESP - Universidade Metodista de São Paulo": 0,
            "UNAERP - Universidade de Ribeirão Preto": 0,
            "UNIMEP - Universidade Metodista de Piracicaba": 0,
            "UNISANTOS - Universidade Católica de Santos": 0,
            "UNICASTELO - Universidade Camilo Castelo Branco": 0,
            "UNISA - Universidade Santo Amaro[15]": 0,
            "UNIVAP - Universidade do Vale do Paraíba": 0,
            "UNOESTE - Universidade do Oeste Paulista": 0,
            "USF - Universidade São Francisco": 0,
            "FIRB - Faculdades Integradas Rio Branco": 0,
            "CBM - Centro Universitário Barão de Mauá": 0,
            "CUSC - Centro Universitário São Camilo": 0,
            "FEBASP - Centro Universitário Belas Artes de São Paulo": 0,
            "FEI - Fundação Educacional Inaciana": 0,
            "FMU - Centro Universitário das Faculdades Metropolitanas Unidas": 0,
            "FTML - Faculdade de Teologia Metodista Livre": 0,
            "IMT - Instituto Mauá de Tecnologia": 0,
            "UNASP - Centro Universitário Adventista de São Paulo": 0,
            "UNIARA - Centro Universitário de Araraquara": 0,
            "UNICEP - Centro Universitário Central Paulista": 0,
            "UNIFAI - Centro Universitário Assunção": 0,
            "UNIFEB - Centro Universitário da Fundação Educacional de Barretos": 0,
            "UNIFEOB - Centro Universitário da Fundação de Ensino Octávio Bastos": 0,
            "UNIFIEO - Centro Universitário FIEO": 0,
            "UNILAGO - União das Faculdades dos Grandes Lagos": 0,
            "UNIMONTE - Centro Universitário Monte Serrat": 0,
            "UNISAL - Centro Universitário Salesiano de São Paulo": 0,
            "UNORP - Centro Universitário do Norte Paulista": 0,
            "UNIRP - Centro Universitário de Rio Preto": 0,
            "BSP - Business School São Paulo": 0,
            "FATEC - Faculdade de Teologia e Ciências": 0,
            "FECAP - Fundação Escola de Comércio Álvares Penteado": 0,
            "ESPM - Escola Superior de Propaganda e Marketing": 0,
            "ESAGS - Escola Superior de Administração e Gestão": 0,
            "FCL - Faculdade Cásper Líbero": 0,
            "FAAP - Fundação Armando Álvares Penteado": 0,
            "Insper - Instituto de Ensino e Pesquisa": 0,
            "FESPSP - Fundação Escola de Sociologia e Política de São Paulo": 0,
            "FRB - Faculdades Integradas Rio Branco": 0,
            "DOMPEDRO - Faculdades Integradas Dom Pedro II": 0,
            "FIO - Faculdades Integradas de Ourinhos": 0,
            "FTT - Faculdade de Tecnologia Termomecânica": 0,
            "FAPCOM - Faculdade Paulus de Comunicação e Tecnologia": 0,
            "UniSãopaulo - Instituto São Paulo de Formação e Especialização Profissional": 0,
            "FZP - Faculdade Zumbi dos Palmares": 0,
            "FEF - Fundação Educacional de Fernandópolis": 0,
            "Faculdade de Ciências Médicas da Santa Casa de São Paulo": 0,
            "CEUNSP - Centro Universitário Nossa Senhora do Patrocínio": 0,
            "ITE - Instituição Toledo de Ensino": 0,
            "UAM - Universidade Anhembi Morumbi": 0,
            "UBC - Universidade Braz Cubas": 0,
            "UMC - Universidade de Mogi das Cruzes": 0,
            "UNG - Universidade de Guarulhos": 0,
            "UniABC - Universidade do Grande ABC": 0,
            "UNIBAN - Universidade Bandeirante de São Paulo": 0,
            "UNIBERO - Centro Universitário Anhanguera de São Paulo": 0,
            "UNICSUL - Universidade Cruzeiro do Sul": 0,
            "UNIFRAN - Universidade de Franca": 0,
            "UNIMAR - Universidade de Marília": 0,
            "UNINOVE - Universidade Nove de Julho": 0,
            "UNIMES - Universidade Metropolitana de Santos": 0,
            "UNISANTA - Universidade Santa Cecília": 0,
            "UNISO - Universidade de Sorocaba": 0,
            "UNISANT'ANNA - Centro Universitário Sant'Anna": 0,
            "USJT - Universidade São Judas Tadeu": 0,
            "AESA - Anhanguera Educacional": 0,
            "FACAMP - Faculdades de Campinas": 0,
            "FACMIL - Faculdade de Administração de São José do Rio Preto": 0,
            "FADI - Faculdade de Direito de Sorocaba": 0,
            "FADISC - Faculdades Integradas de São Carlos": 0,
            "FALS - Faculdade do Litoral Sul Paulista": 0,
            "FAM - Faculdade de Americana": 0,
            "FATEC Luiz Rosa - Faculdade de Tecnologia Prof. Luiz Rosa": 0,
            "FIAP - Faculdade de Administração e Informática Paulista": 0,
            "FIT - Faculdade Impacta Tecnologia": 0,
            "FMS - Faculdade Mario Schenberg": 0,
            "FNC - Faculdade Nossa Cidade": 0,
            "FOC - Faculdades Oswaldo Cruz": 0,
            "JAPI - Faculdade Japi": 0,
            "SLMANDIC - Faculdade de Odontologia e Centro de Pesquisas Odontológicas São Leopoldo Mandic": 0,
            "TECMED - Faculdade de Tecnologia Tecmed": 0,
            "BANDTEC - Faculdade de Tecnologia Bandeirantes": 0,
            "UFS - Universidade Federal de Sergipe": 0,
            "USE - Universidade Estadual de Sergipe": 0,
            "IFS - Instituto Federal de Sergipe": 0,
            "Unit - Universidade Tiradentes": 0,
            "Faculdade Pio Décimo": 0,
            "Faculdade Estácio de Sergipe": 0,
            "FANESE - Faculdade de Administração e Negócios de Sergipe": 0,
            "FAMA - Faculdade Amadeus": 0,
            "FSLF - Faculdade São Luis de França": 0,
            "FASER - Faculdade Sergipana": 0,
            "FACAR - Faculdade de Aracaju": 0,
            "UNIRB - Faculdade Serigy": 0,
            "FAJAR - Faculdade Jardins": 0,
            "Faculdade Atlântico": 0,
            "UniCOC - Sistema COC de Educação": 0,
            "UNINASSAU - Faculdade Maurício de Nassau": 0,
            "UNITINS - Fundação Universidade do Tocantins": 0,
            "IFTO - Instituto Federal do Tocantins": 0,
            "UFT - Universidade Federal do Tocantins": 0,
            "UnirG - Centro Universitário UnirG": 0,
            "CEULP/ULBRA - Centro Universitário Luterano de Palmas": 0,
            "FACTO - Faculdade Católica do Tocantins": 0,
            "FACDO - Faculdade Católica Dom Orione": 0,
            "FACIT - Faculdade de Ciências do Tocantins": 0,
            "FECIPAR - Faculdade de Educação Ciências e Letras de Paraíso": 0,
            "FAPAL - Faculdade de Palmas": 0,
            "FAG - Faculdade Guaraí": 0,
            "FIESC - Faculdade Integrada de Ensino Superior de Colinas": 0,
            "FASEC - Faculdade Serra do Carmo": 0,
            "IEPO - Instituto de Ensino e Pesquisa Objetivo": 0,
            "ITPAC - Instituto Tocantinense Presidente Antônio Carlos": 0,
            "ITPAC de Porto Nacional - Instituto Tocantinense Presidente Antônio Carlos de Porto Nacional": 0,
            "UNEST - União Educacional de Ensino Superior do Médio Tocantins": 0
        }
    ];


    /* for (var x = 0 ; x < 1500 ; x ++){
       all.push({
           abbr: '1'+Math.random().toString(),
           name: '1'+Math.random().toString()
       })
     }*/
    var final = [];
    Object.keys(data2[0]).forEach(function (key) {
        final.push({
            label:key,
            value:Math.random().toString()
        });
    });
  //  var all = [];
  return final
}

